### ISSUE TITLE
Please release a new image to dockerhub.

### ISSUE THREAD

**Issue by VinceCui** [labring/lvscare#30]
@fanux

**Comment by fanux** [comment]
@cuisongliu

**Comment by cuisongliu** [comment]
ghcr.io/labring/lvscare:v1.1.3-beta.2 @VinceCui  using this image

**Comment by VinceCui** [comment]
Thx very much~

**Comment by VinceCui** [comment]
![image](https://user-images.githubusercontent.com/23137196/171147918-b688f174-a8cd-402f-9f0d-cd31cac9f514.png)


@cuisongliu Sorry, i test new image, but i found its version is wrong, please check it.

**Comment by cuisongliu** [comment]
I will release it later

**Comment by fanux** [comment]
@cuisongliu  @VinceCui This is an urgent need, can it be released soon?
