### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by gdlwolf** [labring/lvscare#38]
请教一个问题，以下是我的配置情况：
1、我计划使用的是kubeadm+lvscare方式实现高可用

2、3台master，ip分别是：10.0.20.31、10.0.20.32、10.0.20.33，VIP计划使用：10.0.20.30

3、lvscare的启动参数是：
LVSCARE_OPTS="care \
--vs 10.0.20.30:16443 \
--rs 10.0.20.31:6443 \
--rs 10.0.20.32:6443 \
--rs 10.0.20.33:6443 \
--health-path / \
--health-schem https"

4、kubeadm初始化的时候如果将controlPlaneEndpoint配置成vip：10.0.20.30:16443，则kubeadm初始化失败，如果配置成master01的真实ip:10.0.20.31:6443,则kubeadm初始化成功。

5、当controlPlaneEndpoint配置成master01的真实ip:10.0.20.31:6443,则kubeadm初始化成功后，进行测试。发现如下情况：
	3台master的ipvsadm -Ln均可以看到ipvs均生效。

IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.20.30:16443 rr
  -> 10.0.20.31:6443              Masq    1      0          0  
  
	但是在master01上执行 curl -k https://10.0.20.30:16443时报错：curl: (7) Failed connect to 10.0.20.30:16443; No route to host，如果直接curl -k https://10.0.20.31:6443是正常。
	如果在master02、master03上执行curl -k https://10.0.20.30:16443时又正常。
	
请问可能时哪里出了问题？

**Comment by dyrnq** [comment]
Look like your IP 10.0.20.30 does not have route.You must create link device by manual on every node first.
```bash
ip link add lvscare type dummy
ip addr add 10.0.20.30/32 dev lvscare
```

**Comment by gdlwolf** [comment]
非常感谢，随后试试
